environment:
  NPM_AUTH_TOKEN:
    secure: K8AN+8bCWLe2w8YzZE0HvENwQO0JPoY4fUZQGmH4U6x6WIP/Z1UAIof4OeNXBc8T

  matrix:
    - job_name: Checks
    - job_name: Deploy
      job_depends_on: Checks
    - job_name: Deploy Demo
      job_depends_on: Checks

image: Ubuntu2004
skip_branch_with_pr: true
init:
  - nvm use 14
install:
  - npm install

for:
  -
    matrix:
      only:
        - job_name: Checks
    test_script:
      - npm run typecheck
      - npm run lint
    build: off

  -
    matrix:
      only:
        - job_name: Deploy
    skip_non_tags: true
    build_script:
      - npm run package:build
    before_deploy:
      - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
    deploy_script:
      - npm publish --access public

  -
    matrix:
      only:
        - job_name: Deploy Demo
    skip_non_tags: true
    deploy_script:
      - curl ${DEPLOY_HOOK_URL}
