environment:
  NPM_AUTH_TOKEN:
    secure: K8AN+8bCWLe2w8YzZE0HvENwQO0JPoY4fUZQGmH4U6x6WIP/Z1UAIof4OeNXBc8T
  GIT_EMAIL: shelchkovy@yandex.ru
  GIT_NAME: Yaroslav Shelchkov
  GITHUB_ACCESS_TOKEN:
    secure: MocLhzTvm3CitWDA5mbp6CfpOili6wal8IczthCg+3wJEvH01m+Jyi7DcQPeeGKF
  HEROKU_APP_NAME: screen-cover
  HEROKU_API_KEY:
    secure: jPWq020PLzj6m4aJkjSCJcXuwD/CYjSLNs1tPNPBRP8Hs5YvF0cGJCZR+X/BiSJL

  matrix:
    - job_name: Checks
    - job_name: Deploy
      job_depends_on: Checks
    - job_name: Deploy Demo
      job_depends_on: Checks

image: Ubuntu2004
skip_branch_with_pr: true
init:
  - nvm use 14
  - node -v
install:
  - npm install

for:
  -
    matrix:
      only:
        - job_name: Checks
    test_script:
      - npm run typecheck
      - npm run lint:fix
    after_test:
      - git status
      - echo branch ${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
      - echo build branch ${APPVEYOR_REPO_BRANCH}
      - git config user.email "${GIT_EMAIL}" && git config user.name "${GIT_NAME}"
      - 'git add -A && git commit -m"feat: fix linting"'
      - git push https://shelchkov:${GITHUB_ACCESS_TOKEN}@github.com/shelchkov/screen-cover.git HEAD:${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
      - git status
    build: off

  -
    matrix:
      only:
        - job_name: Deploy
    skip_non_tags: true
    build_script:
      - npm run package:build
    before_deploy:
      - ps: '"//registry.npmjs.org/:_authToken=$env:NPM_AUTH_TOKEN`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
      - npm whoami
    deploy_script:
      - npm publish --access public

  -
    matrix:
      only:
        - job_name: Deploy Demo
    skip_non_tags: true
    build_script:
      - npm run build
    before_deploy:
      - curl https://cli-assets.heroku.com/install.sh | sh
      - heroku -v
    deploy_script:
      - cd build && git init && git config user.email "${GIT_EMAIL}" && git config user.name "${GIT_NAME}" && git config -l
      - git add -A && git commit -m'deploy ${APPVEYOR_REPO_TAG_NAME}'
      - git push -f https://heroku:$${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git HEAD:main
